name: app
description: A new Flutter project.
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  cloud_firestore: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
 

flutter:
  uses-material-design: true
  assets:
    - images/lake.jpg
    - images/Fondo.png
    - images/Ndice1.png
    - images/Ellipse18.png

                
fonts:
  - family: Amiko

  - asset: assets/fonts/Amiko-Regular.ttf
  - asset: assets/fonts/Amiko-Bold.ttf
  - weight: 400 
  - weight: 700

  - family: BerlinSansFB
  - asset: assets/fonts/BerlinSansFB-Regular.ttf
    weight: 400
      
          
         
          