name: appJap
description: Version Beta de la app de idiomas
version: 2.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^0.1.2
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  cloud_firestore: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"
 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
 
flutter:
  uses-material-design: true
  assets:
    - images/lake.jpg
    - images/Fondo.png
    - images/Ndice1.png
    - images/Ellipse18.png

                
fonts:
  - family: Amiko

  - asset: assets/fonts/Amiko-Regular.ttf
  - asset: assets/fonts/Amiko-Bold.ttf
  - weight: 400 
  - weight: 700

  - family: BerlinSansFB
  - asset: assets/fonts/BerlinSansFB-Regular.ttf
    weight: 400
      
          
         
          