// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0MiV2yApg3b7JvWJBKzgpAGWJIp9_Cng',
    appId: '1:482119935852:web:1c46aa16f5d3160847b549',
    messagingSenderId: '482119935852',
    projectId: 'jp-app-b3876',
    authDomain: 'jp-app-b3876.firebaseapp.com',
    storageBucket: 'jp-app-b3876.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI3CqV_9gLaTCQLcsc5cSsxG9MF7qRkho',
    appId: '1:482119935852:android:682fffacc9a6054d47b549',
    messagingSenderId: '482119935852',
    projectId: 'jp-app-b3876',
    storageBucket: 'jp-app-b3876.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwJbdwotAR9Rzzs6N9QFj5iympLgYM7rI',
    appId: '1:482119935852:ios:11bcea205d9d115347b549',
    messagingSenderId: '482119935852',
    projectId: 'jp-app-b3876',
    storageBucket: 'jp-app-b3876.appspot.com',
    iosClientId: '482119935852-vrd321pdk6ld7029m2fkd4he1s24c6ge.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwJbdwotAR9Rzzs6N9QFj5iympLgYM7rI',
    appId: '1:482119935852:ios:11bcea205d9d115347b549',
    messagingSenderId: '482119935852',
    projectId: 'jp-app-b3876',
    storageBucket: 'jp-app-b3876.appspot.com',
    iosClientId: '482119935852-vrd321pdk6ld7029m2fkd4he1s24c6ge.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
